// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64
	UserID    pgtype.Int8
	Action    string
	Details   []byte
	Timestamp pgtype.Timestamptz
}

type FileSharesToUser struct {
	UserFileID       int64
	SharedWithUserID int64
}

type Permission struct {
	ID   int32
	Name string
}

type PhysicalFile struct {
	ID             int64
	Sha256Hash     string
	SizeBytes      int64
	StoragePath    string
	ReferenceCount int32
	CreatedAt      pgtype.Timestamptz
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type Share struct {
	ID            int64
	UserFileID    int64
	ShareToken    string
	IsPublic      pgtype.Bool
	DownloadCount pgtype.Int8
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID                int64
	Email             string
	PasswordHash      string
	StorageQuotaBytes int64
	StorageUsedBytes  int64
	CreatedAt         pgtype.Timestamptz
}

type UserFile struct {
	ID             int64
	OwnerID        int64
	PhysicalFileID int64
	Filename       string
	MimeType       string
	Description    pgtype.Text
	Tags           []string
	UploadDate     pgtype.Timestamptz
}

type UserRole struct {
	UserID int64
	RoleID int32
}
